name: Continuous Integration

on:
  workflow_dispatch:
    inputs:
      controller_url:
        description: 'The URL of AWX/AAP.'
        type: string
        required: true
      controller_username:
        description:
          'The username to log into the controller. One of username/password or
          token needs to be provided.'
        type: string
        required: false
      controller_password:
        description:
          'The password to log into the controller. One of username/password or
          token needs to be provided.'
        type: string
        required: false
      controller_token:
        description:
          'The token to authenticate to the controller. One of username/password or
          token needs to be provided.'
        type: string
        required: false
      controller_timeout:
        description:
          'The timeout in milliseconds to wait for a call to the controller before
          erroring out.'
        required: false
        type: number
        default: 1000
      controller_verify_certificate:
        description:
          "Verify if the controller's certificate is valid. Type string[boolean]"
        required: false
        type: boolean
        default: true
      job_template_id:
        description:
          'The job template id. This is mutually exclusive with
          workflow_job_template_id.'
        type: number
        required: false
      workflow_job_template_id:
        description:
          'The workflow job template id. This is mutually exclusive with
          job_template_id'
        type: number
        required: false
      extra_vars:
        description:
          'Pass extra command line variables to the playbook.'
        type: string
        required: false
      inventory:
        description:
          'Select the inventory containing the hosts you want this job to manage.'
        type: string
        required: false
      scm_branch:
        description:
          'Branch to checkout. In addition to branches, you can input tags, commit
          hashes, and arbitrary refs.'
        type: string
        required: false
      limit:
        description:
          'Provide a host pattern to further constrain the list of hosts that will
          be managed or affected by the playbook.'
        type: string
        required: false
      job_tags:
        description:
          'Tags are useful when you have a large playbook, and you want to run a
          specific part of a play or task. Use commas to separate multiple tags.'
        type: string
        required: false
      skip_tags:
        description:
          'Skip tags are useful when you have a large playbook, and you want to skip
          specific parts of a play or task. Use commas to separate multiple tags.'
        type: string
        required: false
      job_type:
        description:
          "For job templates, select run to execute the playbook. Select check to
          only check playbook syntax, test environment setup, and report problems
          without executing the playbook. Can only be one of 'run', or 'check'"
        required: false
        type: choice
        options:
          - "run"
          - "check"
        default: 'run'
      verbosity:
        description:
          'Control the level of output ansible will produce as the playbook
          executes. Can only be one of 0-5.'
        type: choice
        options:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
        required: false
      diff_mode:
        description:
          'If enabled, show the changes made by Ansible tasks, where supported.'
        type: boolean
        required: false
      credentials:
        description:
          "Select credentials for accessing the nodes this job will be ran against.
          Specify as a list of ID's seperated by commas."
        type: string
        required: false
      credential_passwords:
        description: 'Credentials Passwords.'
        type: string
        required: false
      execution_environment:
        description:
          'The container image to be used for execution. Specify as the ID of the EE.'
        type: number
        required: false
      labels:
        description:
          "Optional labels that describe this job template, such as 'dev' or 'test'.
          Specify as a list of ID's seperated by commas."
        type: string
        required: false
      forks:
        description:
          'The number of parallel or simultaneous processes to use while executing
          the playbook.'
        type: number
        required: false
      job_slice_count:
        description:
          'Divide the work done by this job template into the specified number of
          job slices, each running the same tasks against a portion of the
          inventory.'
        type: number
        required: false
      timeout:
        description:
          'The amount of time (in seconds) to run before the job is canceled.'
        type: number
        required: false
      instance_groups:
        description:
          "Select the Instance Groups for this Job Template to run on. Specify as a
          list of ID's seperated by commas."
        type: string
        required: false

permissions:
  contents: read

jobs:
  test-awx-jt-simple:
    name: Test a simple Job Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Setup Node.js
      #   id: setup-node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version-file: .node-version
      #     cache: npm
      
      - name: Start AWX
        id: start-awx
        uses: irunasroot/action-awx-template@releases/v1
        with:
          controller_url: 
